"""
app.py
------
Multi College Enquiry Chatbot System (Full-Stack Mini Project)

Tech Stack:
- Frontend: HTML, CSS, JavaScript, Bootstrap
- Backend : Python Flask
- Database: MySQL

This project supports 4 colleges under Sri Shanmugha Institutions:
1) Engineering and Technology
2) Pharmacy
3) Nursing
4) Allied Health Science
"""

from __future__ import annotations

import re
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

import mysql.connector
from flask import (
    Flask,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
    g,
    flash,
)
from mysql.connector import Error as MySQLError
from werkzeug.security import check_password_hash, generate_password_hash

# Simple "AI" for FAQ matching:
# - Preferred: scikit-learn TF-IDF cosine similarity
# - Fallback : Python difflib (no external dependency)
try:
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity

    SKLEARN_AVAILABLE = True
except Exception:
    TfidfVectorizer = None  # type: ignore
    cosine_similarity = None  # type: ignore
    SKLEARN_AVAILABLE = False

from config import Config


app = Flask(__name__)
app.config.from_object(Config)


# ------------------------------
# Database helpers (beginner-friendly)
# ------------------------------
def get_db():
    """
    Create a MySQL connection and store it in flask.g for reuse in a request.
    """
    if "db" not in g:
        g.db = mysql.connector.connect(
            host=app.config["MYSQL_HOST"],
            port=app.config["MYSQL_PORT"],
            user=app.config["MYSQL_USER"],
            password=app.config["MYSQL_PASSWORD"],
            database=app.config["MYSQL_DB"],
        )
    return g.db


@app.teardown_appcontext
def close_db(_exception):
    """
    Close DB connection at the end of the request.
    """
    db = g.pop("db", None)
    if db is not None and db.is_connected():
        db.close()


def fetch_all(query: str, params: Tuple[Any, ...] = ()) -> List[Dict[str, Any]]:
    db = get_db()
    cur = db.cursor(dictionary=True)
    cur.execute(query, params)
    rows = cur.fetchall()
    cur.close()
    return rows


def fetch_one(query: str, params: Tuple[Any, ...] = ()) -> Optional[Dict[str, Any]]:
    rows = fetch_all(query, params)
    return rows[0] if rows else None


def execute(query: str, params: Tuple[Any, ...] = ()) -> int:
    db = get_db()
    cur = db.cursor()
    cur.execute(query, params)
    db.commit()
    last_id = cur.lastrowid
    cur.close()
    return last_id


# ------------------------------
# Session + auth helpers
# ------------------------------
def ensure_session_id():
    """
    We store a unique session id so we can save chat history even for visitors.
    """
    if "sid" not in session:
        session["sid"] = str(uuid.uuid4())


def login_required(view_func):
    """
    Simple decorator to protect pages.
    """

    def wrapper(*args, **kwargs):
        ensure_session_id()
        if not session.get("logged_in"):
            return redirect(url_for("login"))
        return view_func(*args, **kwargs)

    # Keep function name for Flask routing
    wrapper.__name__ = view_func.__name__
    return wrapper


def college_required(view_func):
    """
    Decorator: user must select a college before entering dashboard/chat pages.
    """

    def wrapper(*args, **kwargs):
        ensure_session_id()
        if not session.get("logged_in"):
            return redirect(url_for("login"))
        if not session.get("college_id"):
            return redirect(url_for("select_college"))
        return view_func(*args, **kwargs)

    wrapper.__name__ = view_func.__name__
    return wrapper


# ------------------------------
# Password helper (beginner-friendly)
# ------------------------------
def verify_password(stored_password_hash_or_plain: str, provided_password: str) -> bool:
    """
    Supports BOTH:
    1) Hashed passwords (recommended): generated by werkzeug.security.generate_password_hash
    2) Plain text passwords (not recommended, but beginner-friendly for demo DB inserts)

    If the stored value looks like a werkzeug hash, we verify it as a hash.
    Otherwise we compare plain text.
    """
    if not stored_password_hash_or_plain:
        return False
    s = str(stored_password_hash_or_plain)
    if s.startswith("pbkdf2:") or s.startswith("scrypt:"):
        return check_password_hash(s, provided_password)
    return s == provided_password


# ------------------------------
# Captcha helpers (Visitor / Parent login)
# ------------------------------
def generate_captcha() -> Tuple[str, int]:
    """
    Generates a simple math captcha like '7 + 5 = ?'
    Returns: (question_text, answer_int)
    """
    import random

    a = random.randint(2, 9)
    b = random.randint(2, 9)
    op = random.choice(["+", "-"])
    if op == "-":
        if b > a:
            a, b = b, a
        answer = a - b
    else:
        answer = a + b
    return f"{a} {op} {b} = ?", answer


# ------------------------------
# "AI" Chatbot cache (TF-IDF per college)
# ------------------------------
CHATBOT_CACHE: Dict[int, Dict[str, Any]] = {}


def get_college(college_id: int) -> Optional[Dict[str, Any]]:
    return fetch_one("SELECT * FROM colleges WHERE id=%s", (college_id,))


def get_college_details(college_id: int) -> Optional[Dict[str, Any]]:
    return fetch_one("SELECT * FROM college_details WHERE college_id=%s", (college_id,))


def build_chatbot_model(college_id: int) -> Dict[str, Any]:
    """
    Load chatbot questions for a college and build a TF-IDF model.
    """
    rows = fetch_all(
        """
        SELECT id, category, question, answer
        FROM chatbot_questions
        WHERE college_id=%s
        ORDER BY id ASC
        """,
        (college_id,),
    )

    model: Dict[str, Any] = {"rows": rows, "built_at": datetime.utcnow()}

    # If sklearn is installed, use TF-IDF similarity (better matching).
    if SKLEARN_AVAILABLE and rows:
        corpus = [r["question"] for r in rows]
        vectorizer = TfidfVectorizer(stop_words="english")
        X = vectorizer.fit_transform(corpus)
        model.update({"vectorizer": vectorizer, "X": X})

    CHATBOT_CACHE[college_id] = model
    return model


def get_chatbot_model(college_id: int) -> Dict[str, Any]:
    """
    Get cached model if available; otherwise build it.
    """
    if college_id not in CHATBOT_CACHE:
        return build_chatbot_model(college_id)
    return CHATBOT_CACHE[college_id]


def is_hostel_image_request(text: str) -> bool:
    t = text.lower()
    triggers = [
        "hostel image",
        "hostel images",
        "show hostel",
        "show hostel room",
        "hostel room",
        "boys hostel",
        "girls hostel",
    ]
    return any(k in t for k in triggers)


def is_facility_image_request(text: str) -> bool:
    """
    Detects if user is asking for images for facilities like labs, classrooms, library, etc.
    """
    t = text.lower()

    # If user explicitly says image/photo/show/view + facility keyword
    wants_image = any(k in t for k in ["image", "images", "photo", "photos", "picture", "show", "view"])
    has_facility_keyword = any(
        k in t
        for k in [
            "lab",
            "labs",
            "laboratory",
            "classroom",
            "class room",
            "smart class",
            "library",
            "infrastructure",
            "campus",
            "placement",
            "placements",
            "facility",
            "facilities",
        ]
    )

    # Also support direct triggers like "show labs" or "library image"
    direct_triggers = [
        "lab image",
        "labs image",
        "show labs",
        "classroom image",
        "library image",
        "infrastructure image",
        "placement image",
        "campus image",
        "campus facilities",
    ]

    return (wants_image and has_facility_keyword) or any(k in t for k in direct_triggers)


def guess_facility_type(text: str) -> str:
    """
    Returns one of: labs, classrooms, library, infrastructure, placements, campus
    """
    t = text.lower()
    if "lab" in t or "labs" in t or "laboratory" in t:
        return "labs"
    if "classroom" in t or "class room" in t or "smart class" in t:
        return "classrooms"
    if "library" in t:
        return "library"
    if "placement" in t or "placements" in t:
        return "placements"
    if "infrastructure" in t:
        return "infrastructure"
    return "campus"


def guess_hostel_gender(text: str) -> str:
    t = text.lower()
    if "boys" in t:
        return "boys"
    if "girls" in t:
        return "girls"
    return "common"


def clean_text(s: str) -> str:
    s = s.strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s


def get_suggestions(college_id: int) -> List[str]:
    """
    Quick FAQ suggestions shown as chips in UI.
    """
    rows = fetch_all(
        """
        SELECT question
        FROM chatbot_questions
        WHERE college_id=%s
        ORDER BY id ASC
        LIMIT 6
        """,
        (college_id,),
    )
    return [r["question"] for r in rows] if rows else []


def chatbot_reply(college_id: int, user_text: str) -> Dict[str, Any]:
    """
    Returns a dict:
    - type: "text" | "images"
    - reply: string
    - images: [ {url, title} ] (only for type="images")
    - suggestions: list of suggestion strings
    """
    user_text_clean = clean_text(user_text)

    # Special Feature: Hostel images
    if is_hostel_image_request(user_text_clean):
        gender = guess_hostel_gender(user_text_clean)
        imgs = fetch_all(
            """
            SELECT image_filename, title, gender
            FROM hostel_images
            WHERE college_id=%s AND (gender=%s OR gender='common')
            ORDER BY id ASC
            """,
            (college_id, gender),
        )
        if not imgs:
            return {
                "type": "text",
                "reply": "I don’t have hostel images stored yet. Please add images in static/images/hostel and insert rows into hostel_images table.",
                "suggestions": get_suggestions(college_id),
            }

        images_payload = [
            {
                "url": url_for("static", filename=f"images/hostel/{i['image_filename']}"),
                "title": i.get("title") or "Hostel Room",
            }
            for i in imgs
        ]
        return {
            "type": "images",
            "reply": "Here are some hostel room images:",
            "images": images_payload,
            "suggestions": get_suggestions(college_id),
        }

    # Special Feature: Facility images (labs, classrooms, library, infrastructure, placements, campus)
    if is_facility_image_request(user_text_clean):
        facility = guess_facility_type(user_text_clean)
        imgs = fetch_all(
            """
            SELECT image_filename, title, facility_type
            FROM facility_images
            WHERE college_id=%s AND facility_type=%s
            ORDER BY id ASC
            """,
            (college_id, facility),
        )
        if not imgs:
            return {
                "type": "text",
                "reply": (
                    f"I don’t have {facility} images stored yet. "
                    "Please add images inside static/images/facilities and insert rows into facility_images table."
                ),
                "suggestions": get_suggestions(college_id),
            }

        images_payload = [
            {
                "url": url_for("static", filename=f"images/facilities/{i['image_filename']}"),
                "title": i.get("title") or facility.title(),
            }
            for i in imgs
        ]
        return {
            "type": "images",
            "reply": f"Here are some {facility} images:",
            "images": images_payload,
            "suggestions": get_suggestions(college_id),
        }

    # Normal FAQ matching
    model = get_chatbot_model(college_id)
    rows = model["rows"]

    if rows:
        # If sklearn is available, use TF-IDF cosine similarity
        if SKLEARN_AVAILABLE and model.get("vectorizer") is not None and model.get("X") is not None:
            vectorizer = model["vectorizer"]
            X = model["X"]
            user_vec = vectorizer.transform([user_text_clean])
            sims = cosine_similarity(user_vec, X).flatten()
            best_idx = int(sims.argmax())
            best_score = float(sims[best_idx])

            # Threshold decides when the bot is confident
            if best_score >= 0.22:
                answer = rows[best_idx]["answer"]
                return {"type": "text", "reply": answer, "suggestions": get_suggestions(college_id)}

        # Fallback: difflib similarity (works even without scikit-learn)
        import difflib

        qlist = [str(r["question"]).lower() for r in rows]
        scores = [difflib.SequenceMatcher(None, user_text_clean, q).ratio() for q in qlist]
        best_idx = int(max(range(len(scores)), key=lambda i: scores[i]))
        best_score = float(scores[best_idx])
        if best_score >= 0.42:
            answer = rows[best_idx]["answer"]
            return {"type": "text", "reply": answer, "suggestions": get_suggestions(college_id)}

    # Fallback answer (when no match)
    details = get_college_details(college_id) or {}
    contact = details.get("contact_text") or "Please visit the college office or contact the admissions team."
    return {
        "type": "text",
        "reply": (
            "I’m not fully sure about that yet. You can ask about fees, courses, hostel, placements, "
            "admission process, scholarships, transport, labs, infrastructure, library, events, etc.\n\n"
            f"Contact: {contact}"
        ),
        "suggestions": get_suggestions(college_id),
    }


def save_chat_history(college_id: int, user_message: str, bot_reply: str):
    """
    Save chat history to database.
    """
    ensure_session_id()
    execute(
        """
        INSERT INTO chat_history (session_id, user_id, user_type, college_id, user_message, bot_reply, created_at)
        VALUES (%s, %s, %s, %s, %s, %s, NOW())
        """,
        (
            session.get("sid"),
            session.get("user_id"),
            session.get("user_type"),
            college_id,
            user_message,
            bot_reply,
        ),
    )


# ------------------------------
# Routes
# ------------------------------
@app.route("/")
def home():
    ensure_session_id()
    if session.get("logged_in"):
        if session.get("college_id"):
            return redirect(url_for("dashboard"))
        return redirect(url_for("select_college"))
    return redirect(url_for("login"))


@app.route("/login", methods=["GET", "POST"])
def login():
    ensure_session_id()

    # Create captcha for visitor login
    if request.method == "GET":
        question, answer = generate_captcha()
        session["captcha_answer"] = answer
        return render_template(
            "login.html",
            app_name=app.config["APP_NAME"],
            institution=app.config["INSTITUTION_NAME"],
            captcha_question=question,
        )

    user_type = request.form.get("user_type", "")

    try:
        # A) Existing Student (college mail + password in student_login table)
        if user_type == "existing_student":
            email = request.form.get("student_email", "").strip().lower()
            password = request.form.get("student_password", "")

            row = fetch_one(
                "SELECT * FROM student_login WHERE college_email=%s",
                (email,),
            )
            if not row or not verify_password(row["password_hash"], password):
                flash("Invalid student email or password.", "danger")
                return redirect(url_for("login"))

            session["logged_in"] = True
            session["user_type"] = "existing_student"
            session["user_id"] = row["id"]
            session["display_name"] = row.get("student_name") or "Student"

            # For existing student, we can auto set college if available
            if row.get("college_id"):
                session["college_id"] = int(row["college_id"])
                return redirect(url_for("dashboard"))
            return redirect(url_for("select_college"))

        # B) New Student for Admission (register/login using Gmail)
        if user_type == "new_student":
            email = request.form.get("new_email", "").strip().lower()
            password = request.form.get("new_password", "")

            user = fetch_one(
                "SELECT * FROM users WHERE user_type='new_student' AND email=%s",
                (email,),
            )
            if not user:
                flash("Account not found. Please register first.", "warning")
                return redirect(url_for("login"))

            if not verify_password(user["password_hash"], password):
                flash("Invalid email or password.", "danger")
                return redirect(url_for("login"))

            session["logged_in"] = True
            session["user_type"] = "new_student"
            session["user_id"] = user["id"]
            session["display_name"] = user.get("name") or "New Student"
            return redirect(url_for("select_college"))

        # C) Visitor / Parent (name + captcha)
        if user_type == "visitor":
            name = request.form.get("visitor_name", "").strip()
            captcha = request.form.get("captcha", "").strip()

            try:
                captcha_int = int(captcha)
            except ValueError:
                captcha_int = None

            if not name:
                flash("Please enter your name.", "warning")
                return redirect(url_for("login"))

            if captcha_int is None or captcha_int != session.get("captcha_answer"):
                flash("Captcha verification failed. Please try again.", "danger")
                return redirect(url_for("login"))

            # Store visitor as a lightweight user (optional)
            session["logged_in"] = True
            session["user_type"] = "visitor"
            session["user_id"] = None
            session["display_name"] = name
            return redirect(url_for("select_college"))

        flash("Please choose a valid login type.", "warning")
        return redirect(url_for("login"))

    except MySQLError as e:
        flash(f"MySQL error: {e}", "danger")
        return redirect(url_for("login"))


@app.route("/register", methods=["POST"])
def register():
    """
    Register new student (Gmail id + password).
    """
    ensure_session_id()
    name = request.form.get("reg_name", "").strip()
    email = request.form.get("reg_email", "").strip().lower()
    password = request.form.get("reg_password", "")

    if not name or not email or not password:
        flash("Please fill all registration fields.", "warning")
        return redirect(url_for("login"))

    # Small validation (only allow Gmail for demo)
    if not email.endswith("@gmail.com"):
        flash("For this demo, please use a Gmail address (example@gmail.com).", "info")
        return redirect(url_for("login"))

    existing = fetch_one(
        "SELECT id FROM users WHERE user_type='new_student' AND email=%s",
        (email,),
    )
    if existing:
        flash("Account already exists. Please login.", "info")
        return redirect(url_for("login"))

    execute(
        """
        INSERT INTO users (user_type, name, email, password_hash, created_at)
        VALUES ('new_student', %s, %s, %s, NOW())
        """,
        (name, email, generate_password_hash(password)),
    )
    flash("Registration successful! Please login now.", "success")
    return redirect(url_for("login"))


@app.route("/logout")
def logout():
    session.clear()
    flash("Logged out successfully.", "success")
    return redirect(url_for("login"))


@app.route("/select-college", methods=["GET", "POST"])
@login_required
def select_college():
    ensure_session_id()
    if request.method == "GET":
        colleges = fetch_all("SELECT * FROM colleges ORDER BY id ASC")
        return render_template("select_college.html", colleges=colleges)

    college_id = request.form.get("college_id")
    if not college_id:
        flash("Please select a college.", "warning")
        return redirect(url_for("select_college"))

    session["college_id"] = int(college_id)
    return redirect(url_for("dashboard"))


@app.route("/dashboard")
@college_required
def dashboard():
    ensure_session_id()
    college_id = int(session["college_id"])
    college = get_college(college_id)
    details = get_college_details(college_id) or {}

    # courses_text is stored as a user-friendly string in DB for beginners
    courses = (details.get("courses_text") or "").split("\n")
    courses = [c.strip() for c in courses if c.strip()]

    gallery = [
        url_for("static", filename="images/gallery/campus_1.svg"),
        url_for("static", filename="images/gallery/campus_2.svg"),
        url_for("static", filename="images/gallery/campus_3.svg"),
    ]

    return render_template(
        "dashboard.html",
        college=college,
        details=details,
        courses=courses,
        gallery=gallery,
    )


@app.route("/chat")
@college_required
def chat():
    ensure_session_id()
    college_id = int(session["college_id"])
    college = get_college(college_id)
    suggestions = get_suggestions(college_id)
    return render_template("chat.html", college=college, suggestions=suggestions)


@app.route("/api/chat", methods=["POST"])
@college_required
def api_chat():
    ensure_session_id()
    college_id = int(session["college_id"])
    data = request.get_json(silent=True) or {}
    message = (data.get("message") or "").strip()

    if not message:
        return jsonify({"ok": False, "error": "Empty message"}), 400

    payload = chatbot_reply(college_id, message)
    save_chat_history(college_id, message, payload.get("reply", ""))
    return jsonify({"ok": True, **payload})


@app.route("/api/enquiry", methods=["POST"])
@college_required
def api_enquiry():
    """
    Save enquiry form data.
    """
    ensure_session_id()
    college_id = int(session["college_id"])
    data = request.get_json(silent=True) or {}

    name = (data.get("name") or session.get("display_name") or "").strip()
    email = (data.get("email") or "").strip()
    phone = (data.get("phone") or "").strip()
    message = (data.get("message") or "").strip()

    if not name or not message:
        return jsonify({"ok": False, "error": "Name and message are required"}), 400

    execute(
        """
        INSERT INTO enquiries (user_id, user_type, college_id, name, email, phone, message, created_at)
        VALUES (%s, %s, %s, %s, %s, %s, %s, NOW())
        """,
        (
            session.get("user_id"),
            session.get("user_type"),
            college_id,
            name,
            email,
            phone,
            message,
        ),
    )
    return jsonify({"ok": True})


@app.route("/health")
def health():
    """
    Quick health-check endpoint.
    """
    try:
        db = get_db()
        ok = db.is_connected()
        return jsonify({"ok": bool(ok)})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 500

if __name__ == "__main__":
    import webbrowser
    webbrowser.open("http://127.0.0.1:5000")
    app.run(debug=True)
    
if __name__ == "__main__":
    # NOTE: debug=True is good for learning; turn off for production.
    app.run(debug=True)
